---
- name: Install bind-utils package
  ansible.builtin.dnf:
    name: bind-utils
    state: present

- name: Install bind package
  ansible.builtin.dnf:
    name: bind
    state: present

- name: Install procps-ng package
  ansible.builtin.dnf:
    name: procps-ng
    state: present

- name: Create localnet zone file from template
  ansible.builtin.template:
    src: templates/localnet.zone.j2
    dest: /var/named/localnet.zone
    owner: named
    group: named
    mode: "0640"

- name: Configure named.conf for localnet zone
  ansible.builtin.blockinfile:
    path: /etc/named.conf
    block: |
      zone "localnet" IN {
          type master;
          file "localnet.zone";
          allow-update { none; };
      };

- name: Configure named.conf to listen on all IPv4interfaces
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: '^(\s*)(listen-on port 53 \{ 127\.0\.0\.1; \};)'
    line: '\1listen-on port 53 { any; };'
    backrefs: yes

- name: Configure named.conf to listen on all IPv6 interfaces
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: '^(\s*)(listen-on-v6 port 53 \{ ::1; \};)'
    line: '\1listen-on-v6 port 53 { any; };'
    backrefs: yes

- name: Configure named.conf to answer queries from any source
  ansible.builtin.lineinfile:
    path: /etc/named.conf
    regexp: '^(\s*)(allow-query \{ localhost; \};)'
    line: 'allow-query { any; };'
    backrefs: yes

- name: Restart named service
  ansible.builtin.service:
    name: "named"
    enabled: true
    state: restarted
