---
- name: Install bind-utils package
  ansible.builtin.dnf:
    name: bind-utils
    state: present

- name: Install bind package
  ansible.builtin.dnf:
    name: bind
    state: present

- name: Create localnet zone file from template
  ansible.builtin.template:
    src: templates/localnet.zone.j2
    dest: /var/named/localnet.zone
    owner: named
    group: named
    mode: "0640"

- name: Configure named.conf for localnet zone
  ansible.builtin.blockinfile:
    path: /etc/named.conf
    block: |
      zone "localnet" IN {
          type master;
          file "localnet.zone";
          allow-update { none; };
      };

- name: Restart named service
  ansible.builtin.service:
    name: "named"
    enabled: true
    state: restarted
